/** FormIQ - Technical console theme. */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#a1a1aa",
        "on-primary": "#0e0e0e",
        "primary-container": "#a1a1aa",
        "on-primary-container": "#0e0e0e",
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#a1a1aa",
        outline: "#849495",
        "outline-variant": "rgba(161, 161, 170, 0.2)",
        secondary: "#c8c6c5",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "1px",
        "pane-padding": "16px",
        "margin-sm": "8px",
        "margin-md": "16px",
        "margin-lg": "24px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "body-lg": ["Geist"],
        "data-lg": ["JetBrains Mono"],
        "data-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "300" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "300" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-lg": ["24px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "400" }],
        "data-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
